[package]
edition = "2024"
license = "MIT OR Apache-2.0"
name = "placid"
version = "0.1.0"

[features]
default = ["fn-impl"]
fn-impl = []

[dependencies]
thiserror = {version = "2.0", default-features = false}
